export const CATEGORY_COLORS = [
  { name: "Red", value: "#ef4444" },
  { name: "Orange", value: "#f97316" },
  { name: "Amber", value: "#f59e0b" },
  { name: "Yellow", value: "#eab308" },
  { name: "Green", value: "#22c55e" },
  { name: "Emerald", value: "#10b981" },
  { name: "Teal", value: "#14b8a6" },
  { name: "Cyan", value: "#06b6d4" },
  { name: "Blue", value: "#3b82f6" },
  { name: "Indigo", value: "#6366f1" },
  { name: "Purple", value: "#a855f7" },
  { name: "Pink", value: "#ec4899" },
  { name: "Slate", value: "#64748b" },
] as const;

// Common icons mahasiswa di Eropa konteks
export const CATEGORY_ICONS = [
  { name: "Food", value: "🍔" },
  { name: "Groceries", value: "🛒" },
  { name: "Transport", value: "🚇" },
  { name: "Housing", value: "🏠" },
  { name: "Utilities", value: "💡" },
  { name: "Education", value: "📚" },
  { name: "Books", value: "📖" },
  { name: "Entertainment", value: "🎬" },
  { name: "Shopping", value: "🛍️" },
  { name: "Healthcare", value: "⚕️" },
  { name: "Travel", value: "✈️" },
  { name: "Fitness", value: "💪" },
  { name: "Coffee", value: "☕" },
  { name: "Mobile", value: "📱" },
  { name: "Internet", value: "📶" },
  { name: "Salary", value: "💼" },
  { name: "Scholarship", value: "🎓" },
  { name: "Family", value: "👨‍👩‍👧" },
  { name: "Gift", value: "🎁" },
  { name: "Other", value: "📌" },
] as const;
